name: MineIt
main: com.rogermiranda1000.mineit.MineIt
version: 0.5
author: rogermiranda1000
commands:
  mineit:
    description: Create portals
    usage: /<command>
permissions:
  mineit.create:
    description: Create mines
    default: op
  mineit.remove:
    description: Remove mines
    default: op
  mineit.open:
    description: Open the MineIt inventory
    default: op
  mineit.stagelimit:
    description: Change the mine's stage limit
    default: op